### ISSUE TITLE
Ticket #1829 - Quindar App - AngularJS + widgets: Ground Track

### ISSUE THREAD

**Issue by mkakoi** [audacyDevOps/quindar-angular#13]
Add AngularJS structure to existing ground plot  widgets, and update github quindar project. Merge codes with Github  master project.

# User Story
As a developer, I can refactor existing ground plot widgets into AngularJS directive and controller, so that  they can work with Quindar gridster framework.

# Tasks

 * Onboarding  with AngularJS directive. (assumption: complete AngularJS onboarding  reading list). Refer to the AngularJS directive template below.
 * Convert Widget 2 (ground track: [https://github.com/audacyDevOps/quindarWidgets/blob/master/quindar_v6.html quindar_v6.html]) to AngularJS structure
   * Refactor the ground plot and track from tracks_v3_stream.js using AngularJS directive
   * Update app.js in GitHub quindar-angular project by adding this new lineplot directive in the $scope.widgetDefinitions config data.
   * Manual testing
 * Merge local branch with github master project

## Definition of Done
* create github project to publish standalone ground track widget
github repo name: quindar-groundtrack
provide code example for #1, similar to angular-d3 or angular-flot

* create a branch under github repo quindar-angular
to integrate ground track widget with quindar app 
details under the ticket task to add widget definition

# Reference

## How to Add Directive to quindar-angular
* Create a branch
* Define a new, independent AngularJS directive under /app/directive, e.g. "groundtrack.js"
* Register your new directive in quindar-angular controller (https://github.com/audacyDevOps/quindar-angular/blob/master/app/controllers/index08aControllers.js), e.g.
```  
 $scope.dashboards = {
      '1': {
        id: '1',
        name: 'Basic',
        widgets: [{
          col: 0,
          row: 0,
          sizeY: 1,
          sizeX: 2,
          name: "Page 1 - Line Plot",
          directive: "quindarlinechart"
        }, {
          col: 2,
          row: 0,
          sizeY: 1,
          sizeX: 1,
          name: "Page 1- Countdown Clock",
          directive: "wttime"
        }
       // RayL:  add your new directive here
       ]
      },

```
also you need to register in the widget definition section too:
```
var widgetDefinitions = [
      {
        name: 'Line Plot',
        directive: 'quindarlinechart',
        style: {
          width: '33%'
        }
      },
      {
        name: 'Countdown Clock',
        directive: 'wttime',
        style: {
          width: '33%'
        }
      },
// RayL: add your directive definition here
```
Once you register your directives, you can do a regression test for your branch.

**Comment by audacyDevOps** [comment]
solution is now available in https://github.com/audacyDevOps/quindar-groundtrack
