### ISSUE TITLE
Ticket #1205 - Quindar app JavaScript package management

### ISSUE THREAD

**Issue by rayymlai** [audacyDevOps/quindar-angular#2]
Current Quindar Web pages and backend NodeJS app use many types of JavaScript and CSS using 3 different packaging tools: 
* NodeJS package manager NPM, 
* bower
* manual download. 

None of them take care of Web pages packages.

## Goals
We want to standardize how we manage packages for both client side web pages and backend app. 

What problems we try to solve:
* Quindar-widgets and quindar-angular contain JS/CSS packages from many third-parties embedded into the code base, and in some cases, the software library versions are out of date. We want to structure the packages in a way that we can easily pull the latest version and deploy.
* This package task is to verify if ticket #1172 backend integration is complete, such that all JS/CSS subfolders follow Yeoman's style, e.g. /app/factories, /app/directives, /images, /config.
* For custom packages where their source is located in GitHub (or alike), we need to structure the packages that they can be pulled directly (e.g. via Grunt) from the source during deploy phase. We don't want to manually copy.
* In order to speed up client-side Web browser performance (not server side JS), we want to aggregate the JS packages and minify them into 1-2 JS file.  We also want to leverage if there is any automated way to update index.html (or *.html under /app/views if appropriate) without manual changes every time a package is added or updated.

Options are:
* Backend - NPM, bower
* Front-end - napa, component (obsolete), volo, npm with browsify, spm, jspm, duo, webpack, ender, jam, normalize.io

## Expected outcome
Simplify the JavaScript/CSS packages so that developers don't need to use a large number of dependencies JS/CSS in HTML Web pages. Reorganize the server side packages so that developers don't need to install many local copies for testing.

* Automated script (e.g. Gruntfile) to aggregate and minify JavaScript files
* Automated script (e.g. Gruntfile) to update index.html after JavaScript aggregation/minification, if feasible.
* Automated script to pull custom packages (e.g. quindar-groundtrack, angular-nvd3) into quindar-angular
* New template or process for package changes.  We need to synchronize all quindar-angular, quindar-platform, etc to adopt this new template or process.

## Use Cases
* quindar-angular client-side (e.g. *.js in index.html) need to be packaged in 1 to 2 .js files to speed up performance. We need to automate the process to (1) create a manifest or bill of materials for all *.js used in HTML pages, (2) refactor the index.html so that the grunt script will read the manifest and insert the consolidated .js every time the automated build is done.
* quindar-angular server-side (e.g. server.js, all require('xxx') in server side .js) need to register the backend components in package.json. There is a buildme.ssh to run "npm install". We need to make sure if all versions are latest and compatible, e.g. ensure automated test from separate ticket will do regression test for new package versions.
* same use case for quindar-platform client-side
* same use case for quindar-platform server side

## Tasks
* Clean up and organize (e.g. standardize folder structure as per Yeoman) current Quindar index.html packages (JS, CSS)
  - Validate current github quindar-angular project which has cleaned up the list of packages
* Select a package management tool.
   - Familiarize how to use napa / duo / browsify on client side packaging
   - Validate current proposed strategy:  (1) use napa for client-side JS/CSS packaging. (2) use npm for server-side JS/CSS packaging based on package.json based on previous familiarization task.
   - Tutorial: define a Gruntfile to use napa to create a consolidated JS from multiple Github projects and/or CDN sources, and update append the <script src=xxx></script> in the index.html. (Context: quindar uses a lot of open source JS/CSS, which may reside in Github or CDN public sources).
   - Update wiki on the rationale and instructions (e.g. tutorial example)
* Move custom packages to separate github projects - dependency for earlier task above
* Write Gruntfile to package + minify client side packages, and update index.html.  https://github.com/DataTorrent/malhar-angular-dashboard is a good example.
  - Write Gruntfile to package server side packages. Update package.json.
  - Update github projects (quindar-angular, quindar-platform)
  - Work with DevOps to update Jenkins build job
* Verify the backend JS/CSS packaging standard (e.g. folder structure, naming convention) in quindar-platform, quindar-angular, quindar-lineplot and quindar-groundtrack if they follow consistent package.json using NPM.
  - fix any discrepancy in these projects if needed.

## Context 
Scott Zhang reviewed our GitHub quindar project and found out a couple of gaps in client side and server side package management. This will impact our productivity.

## Reference
http://www.slant.co/topics/1488/~front-end-package-managers
https://github.com/wilmoore/frontend-packagers
http://jamie-wong.com/2014/11/29/the-js-packaging-problem/

### use cases for client-side package manager
* you have a mix of external and home-grown JavaScripts that you need to add to your HTML Web pages
* you need good ways to manage these packages, e.g. store home-grown JS and CSS in github, where you can run test automation when checked in. 

Once all your home-grown JS and CSS files are in Github, you can run package manager to pull your JS/CSS files from Github, and install in your NodeJS web server (deploy and install).

## Options for package managers
* Napa ​https://github.com/shama/napa
* Duo ​https://github.com/duojs/duo
* NPM + browsify https://github.com/substack/node-browserify

Other options 
* bower ​http://docs.asp.net/en/latest/client-side/bower.html (no obvious benefits when compared to NPM)
* jspm ​https://github.com/jspm/jspm-cli (performance issues)
* components ​https://github.com/componentjs/component (obsolete, not supported any more)
* webpack ​https://github.com/webpack/webpack (config file is too difficult to use)
* ender ​https://github.com/ender-js/Ender (registry not made for browsers)
* jam ​http://jamjs.org/ (forced use of AMD -> limited libraries)
* volo ​https://github.com/volojs/volo (does not use registry to register components)
* normalize.io ​https://github.com/normalize (not yet completed)

**Comment by michael-mckenna-audacy** [comment]
Progress Report:

Complete:
- Automated dependency update, automated concatenation and minification of script calls, both css and js files, and html editing all through grunt and napa.
- Demo on how to use grunt uploaded to github quindar-angular unde the grunt+napa branch (titled "intro.md").

To Be Completed:
- Standard template for grunt integration in all quindar projects such as platform

**Comment by michael-mckenna-audacy** [comment]
Update 7/7/16 -- MM

Complete:

1) Automated grunt tasks:
- Concatenation and minification of all Javascript and CSS files,including cdn files
- Editing html file to compile multiple script calls into one script call to minified file
- Pull dependencies from third parties via napa in package.json

2) Gruntfile.js written into grunt+napa branches in both quindar-angular and quindar-platform repositories

3) Tutorial for using grunt and napa with quindar-angular as an example app found in grunt+napa branch of quindar-angular ("intro.md")

4) General template for using grunt and napa in qiundar apps found in grunt+napa branch of quindar-platform ("intro.md")

Next Steps:

1) Automating automated grunt tasks
- Each grunt task that automates part of the development process requires manual setup by developer or devOps team, slowing the initial development process
- To speed up the process, we are working develop an automated setup and call of each of those automated tasks with one command line call
- First we will investigate the plausibility of such automation, then enact if possible.

**Comment by michael-mckenna-audacy** [comment]
Ticket Complete - 7/8/16

- Goal: organize central repository for all third party code updates both front and back end
- Met: manually updating package.json "dependencies" section to match github standards by audacyDevOps. Store cdn files locally as mini files into "dist" folder to use for concatenation.

- Goal: lower load time of front end packages; lower number of script calls in index.html
- Met: manually copy files and paste over to one large concatenated file of all .js or all .css files. Manually replace index.html script calls with one script call to concatenated file. Alternatively use grunt tasks as described in the "grunt+napa" branch to concatenate all necessary files and edit index.html automatically after manual configuration.

Next steps:
- After completing ticket 1308 (FOSS Documentation) automate the grunt automations to replace manual developer inputs.

**Comment by michael-mckenna-audacy** [comment]
* Final approach
  - manually copy-and-paste third party dependencies, and concatenate into 1 single JS/CSS. This reduces page load time
  - add client side packages in package.json as single source of info for update management

* Reshuffle order of loading JS/CSS dependencies, and test OK
* Verified package OK
* Consolidate docs into readme.md
* Standardize folder structure and filename naming convention as per project standard

'''Next Steps'''
* After Aug 1, we will implement automated scripts via napa and grunt to concatenate and minify third party scripts read from index.html, then edit index.html to call new file. This will all be executed from one to a few command line prompts.
