### ISSUE TITLE
Ticket #1202 DevOps - Quindar widgets test scripts

### ISSUE THREAD

**Issue by rayymlai** [audacyDevOps/quindar-angular#6]
Add JavaScript and REST API unit tests to cover both positive and negative test cases for Quindar widgets.

# User Story
As a developer, I can validate if my Quindar application runs without critical errors by using automated unit tests via Jenkins continuous integration.

# Tasks
## On-boarding 
on JavaScript unit testing tools: Mocha, Chai, Jasmine 
  * Use Mocha scripting because we can automate both REST API, Jasmine/Chai for UI web page testing. Refer to ticket #1210 reading list and notes for details.
  * Create a hello world type test script for 1 quindar widget 

## Manual test 
for (1) quindar-angular, and (2) quindar-platform admin UI
* quindar widgets URL: http://widgets.audacy.space
* quindar platform admin UI URL: http://platform.audacy.space:7902

### Widgets: Positive test cases
* Test expected input/output for each Quindar widget directive (e.g. functions defined in each .js)
 * Test number, string, date and email format in each UI data input fields, e.g. drop-down box, button
 * Test if each UI widget feature handles the expected input and output, e.g. push "resume" button should resume plotting the graph
 * Check if there is any global variable or unused data element in JS

### Widgets: Negative test cases
* Test each UI element (e.g. button, drop down box) handles invalid cases, e.g. specifying invalid width and height for each widget directive should return error message
* Test extreme cases for data input field of each widget, e.g. number field > 999999999999, string field handles
* Test coverage, e.g.
  - Add 2 pages, delete 3 pages, save, restore widgets. open a new browser to see if you see those changes
  - Delete all pages, save. open a new browser to see if you see all blank pages. Try different browsers to see compatibility.
  - edit widget settings, add special characters or javascript to see if it breaks or crashes the app
  - edit widget settings to have negative numbers for width, column, height, row, etc to see if it breaks or crashes the app
  - lineplot widget:   load, plot, pause, pan, and hit multiple special characters or mouse actions to see if it breaks or crashes the app
  - ground track widget: connect, stream, clear, stop and hit multiple special characters or mouse actions to see if it breaks or crashes the app
  - for both widgets, find out any combination of key sequences that may break or crash the app

### Platform admin UI
  - Clear database (Database | Vehicle), Create 1 new data (e.g. from Data Generator | Vehicle | enter generated data: 1) and verify if you see 1 new data added under Data Browser and also from Metrics

  - Re-try the previous steps with 10, or 20, or 100 to see if all data points are created correctly
  - check all API docs are matching actual programs, e.g. http://platform.audacy.space:7902/api should match /app/scripts/coreAdmin.js code comments and app.get() or app.post() function definitions

## White-box testing
* Study UI and widget source codes ​https://github.com/audacyDevOps/quindar-angular and ​https://github.com/audacyDevOps/quindarWidgets 
and define (1) positive and (2) negative test cases

### Widgets Positive test cases
  * Test expected input/output for each Quindar widget directive (e.g. functions defined in each .js)
  * Test number, string, date and email format in each UI data input fields, e.g. drop-down box, button
  * Test if each UI widget feature handles the expected input and output, e.g. push "resume" button should resume plotting the graph
  * Check if there is any global variable or unused data element in JS 

### Widgets Negative test cases
  * Test each UI element (e.g. button, drop down box) handles invalid cases, e.g. specifying invalid width and height for each widget directive should return error message
  * Test extreme cases for data input field of each widget, e.g. number field > 999999999999, string field handles
  * Test coverage - test if each parameter in a function is all covered, e.g. function x(a,b,c) - permutate each test case for x(a,_,_), x(a,b,_), ... where _ denotes null data input. 

## Automated frontend scripts
* Add error handling structure in existing code base. Refer to https://www.joyent.com/developers/node/design/errors for details.

* Write Mocha scripts for 
  * Quindar dashboard, e.g. add/change/clear grids
  * Line plot, e.g. start/stop/resume, use API data source, use data streaming data source
  * Ground track, e.g. start/stop/resume, use API data source, use data streaming data source 

# Appendix - Onboarding with JavaScript testing tools
* Mocha ​https://codeforgeek.com/2015/07/unit-testing-nodejs-application-using-mocha/
* Jasmine ​​http://jasmine.github.io/
* Chai ​​http://chaijs.com/ 

## Getting started with Jasmine
* create a file called a.spec.js:

```
var frisby = require("frisby");
var serverEndpoint = "http://localhost:8081";
var serviceGetPositionAll = "/telemetry/position/unit/all";
var serviceGetPositionSamples = "/telemetry/position/unit/samples";

describe("A suite", function() {

    it("contains spec with an expectation", function() {

        expect(true).toBe(true);

    });

});

describe("REST API - get sample position telemetry data", function() {

    it("GET /telemetry/position/unit/samples", function(err, res, body) {

        frisby.create('GET JSON data with parameters').get("http://localhost:8081/telemetry/position/unit/samples").expectStatus(200)

    });

});
```

Your server side code (filename data02.js) should contain:

```
var express = require('express');
var app = express();
var fs = require("fs");
var mongoose = require('mongoose');
var dbConnectionURI = "mongodb://data01.audacy.space:11001/telemetry";
var bodyParser = require("body-parser");

app.use(bodyParser.urlencoded());
app.use(bodyParser.json());

    var attitudeSchema = new mongoose.Schema({

        vehicleId: String,timestamp: Number,q1: Number,q2: Number,q3: Number,q4: Number

    }, { collection: 'attitude'});

    var positionSchema = new mongoose.Schema({

        vehicleId: String,timestamp: Number,x: Number,y: Number,z: Number,vx: Number,vy: Number,vz: Number

    }, { collection: 'position'});

    var vehiclesSchema = new mongoose.Schema({

        deviceId: String,timestamp: Number,value: Number,calibrationFactor: String,uom: String,alertHigh: Number,warnHigh: Number,alertLow: Number,warnLow: Number

    }, { collection: 'vehicles'});

app.get('/telemetry/position/unit/samples', function (req, res) {

    fs.readFile( __dirname + "/" + "position.json", 'utf8', function (err, data) {

        res.status(200);res.setHeader('Content-Type', 'application/json');res.header("Access-Control-Allow-Origin", "*");res.header("Access-Control-Allow-Headers", "X-Requested-With");var foo = "{ \"status\": 200, \"message\": \"retrieve all position data points\", \"data\":" + data + "}";res.end(foo);

    });

})
```

skip the rest

    app.use(express.static(__dirname + '/'));var server = app.listen(8081, function () {

    var host = server.address().addressvar port = server.address().port

    console.log("Audacy Data Service backend listening at http://%s:%s", host, port)

})

##  Setting up Jasmine + Frisby
Assuming you need to write an automated test script for a list of REST APIs. You have a NodeJS web server running under http://localhost:8081 on a separate host. Your REST API may look like:

`http://localhost:8081/position/unit/all`

Now, your Jasmine script "a.spec.js" should check:
* check if the web server is alive
* verify if each REST API is working as expected by returning response code 200
* check if each REST API returns the right data, e.g. the returned data should contain 1 element (size = 1)
* verify if your REST API supports cross-domain CORS
* validates if you can mimick multiple clients running the same test, e.g. test if 3+ users can access the same data without issues

* Jasmine seems to be much simpler than Mocha for setup. 
  * Plus: Min 3 lines of codes to start. Less runtime issues since it does not use the dependency "should" ("should" does not check null value by default, and thus creating many runtime errors easily) 
  * Minus: Timeout errors even when checking for success (http response code 200) against Web pages hosted on localhost 
* Recommendation - don't use Jasmine for API testing because the overhead to connect to REST API is big, and thus it generates timeout exception 

### How to Set up Jasmine
* Using npm, install "jasmine", "jasmine-node" and "express" dependencies 
* Check your PATH variable can find "jasmine-node", e.g. export PATH=$PATH:/home/xxx/node_modules/jasmine_node/bin 
* Your unit test script must contain "spec.js", e.g. jasmine01.spec.js. If your test script does not have the suffix "spec.js", it will return 0 test, 0 assertion, etc. 

### Unit Testing Log Details
* start your backend server by the command "node data01.js" 
* start your unit test by the command "jasmine-node a.spec.js" 

Test result:

```
[root@45260927c557 tutorial]# jasmine-node a.spec.js
..

Failures:

    1) REST API - get sample position telemetry data GET /telemetry/position/unit/samples

        Message:

            timeout: timed out after 5000 msec waiting for spec to complete

        Stacktrace:

            undefined

Finished in 5.104 seconds
2 tests, 2 assertions, 1 failure, 0 skipped
```
## Getting started with Mocha
Assuming you need to write an automated test script for a list of REST APIs. You have a NodeJS web server running under http://localhost:8081 on a separate host. Your REST API may look like:

`http://localhost:8081/position/unit/all`

Now, your Mocha script "unitest01.js" should check:
* check if the web server is alive
* verify if each REST API is working as expected by returning response code 200
* check if each REST API returns the right data, e.g. the returned data should contain 1 element (size = 1)
* verify if your REST API supports cross-domain CORS
* validates if you can mimick multiple clients running the same test, e.g. test if 3+ users can access the same data without issues

 ```
horologium:nodejs ray$ mocha --verbose --timeout 30000 unitest01.js

    REST API - get telemetry data (3 types)

# of records=4323

    ✓ GET /position/unit/all (1367ms)

# of records=4323

    ✓ GET /attitude/unit/all (1053ms)

# of records=867

    ✓ GET /vehicles/unit/all (618ms)

    3 passing (3s)
```

### Mocha - sample test scripts

```
var supertest = require("supertest");
var should = require("should");
```

REST API service endpoints
```
var serverEndpoint = "http://localhost:8081";
var serviceGetPositionAll = "/telemetry/position/unit/all";
var serviceGetPositionSamples = "/telemetry/position/unit/samples";
var serviceGetAttitudeAll = "/telemetry/attitude/unit/all";
var serviceGetAttitudeSamples = "/telemetry/attitude/unit/samples";
var serviceGetVehiclesAll = "/telemetry/vehicles/unit/all";
var serviceGetVehiclesSamples = "/telemetry/vehicles/unit/samples";

var server = supertest.agent(serverEndpoint);
```

Test #1 - get telemetry position - all
```
describe("REST API - get telemetry data (3 types)",function(){

    it("GET /position/unit/all",function(done){

        server = supertest.agent(serverEndpoint);
        server.get(serviceGetPositionAll)
        .expect("Content-type",/json/)
        http status response code 200 = OK, no error
        .expect(200)
        .expect('access-control-allow-origin', '*')
        .expect('access-control-allow-headers', 'X-Requested-With')

    .end(function(err,res) {

        console.log("# of records=" + res.body.data.length);
        res.header['Access-Control-Allow-Origin'.toLowerCase()].should.equal('*');
        res.header['access-control-allow-origin'].should.equal('*');
        res.status.should.equal(200);
        Object.keys(res.body).length.should.not.equal(1);
        done();

    });

    });
```

**Comment by shalininegi** [comment]
# Manual Testing
Tester can manually execute test cases without using automation tools. Any new application must be manually tested before its testing can be automated. Manual testing requires more efforts but it is mandatory to check automation feasibility.

# Black box testing
Manual testing front end application to check the functionality of all buttons. For example, drop down box, click add page, add widgets, add save, add clear buttons and tabs. Also, checking positive and negative test cases for widgets. For instance, test number, string, date and email format in each UI data input fields.

# Bug Report
|Test Description|Prerequisites of the test|Action Performed |Expected Output|Actual Output |  Test Evidence|Steps taken to correct it|
| ----| ----|----|----|----|-----|-----|
|Test each Quindar widget directives|Git clone quindar-angular|Testing numbers and string format in each UI data input fields|Wigets work as expected| All buttons should function with positive numbers|Able to view changes on screen| Changed code to expect input as positive numbers|
|Test if each UI widget feature handles the expected input and output|Git clone quindar-angular |Push "resume" button should resume plotting the graph|Graph plotted|Resume button should plot graph|Able to see graph on screen| Changed code to implement the effect|
|Test each UI element|Git clone quindar-angular |Clicking UI elements|Work as expected|Return functionality for each UI elements|Able to view each functionality| Verified each button is working |
|Test ground track widgets|Git clone quindar-angular |Clicking UI elements,e.g. connect, stream, clear, stop|Able to perform function as per click|Return functionality for each buttons|Able to view each functionality on screen| Changed code|
|Test widgets alignment|Git clone quindar-angular |Alignment of widgets |Able to display widgets with properly aligned|Widgets are aligned properly|Able to see widgets properly aligned| Modified  code|
|Test extreme cases for lineplot widget|Git clone quindar-angular |Handles invalid cases e.g. load, plot, pause, pan and hit multiple mouse actions to see if it breaks or crashes the app|Able to load pages |Handle multiple mouse clicks|Able to view widgets on dashboard|Changed code|
|Test extreme cases for ground track widget|Git clone quindar-angular |Handles invalid cases e.g. connect, stream, clear, stop and hit multiple mouse actions to see if it breaks or crashes the app|Able to load pages |Handle multiple mouse clicks|Able to view widgets on dashboard|Changed code|
|Test extreme cases for both widget|Git clone quindar-angular |Any combination of key sequences that may break or crash the app|Didn't break app |App loaded successfully|Successfully view app|Changed code|
|Test extreme cases for widget|Git clone quindar-angular |Add pages, delete pages, save, and restore widgets. Open browser to view if you can see those changes|Able to view changes|Changes made are successful|View modified app|Redesign code for desired result|
|Testing compatibility |Git clone quindar-angular |Test to check if it works on different browsers and mobile devices e.g. iOS and Android. |Able to view our app|Working successfully |App can be viewed on different browser and mobile devices |Code redefined|
